const CITIES = [
  { name: 'canberra', country: 'australie', continent: 'océanie', lon: 149.13, lat: -35.28 },
  { name: 'port-vila', country: 'vanuatu', continent: 'océanie', lon: 168.32, lat: -17.73 },
  { name: 'port moresby', country: 'papouasie-nouvelle-guinée', continent: 'océanie', lon: 147.18, lat: -9.48 },
  { name: 'pyongyang', country: 'corée du nord', continent: 'asie', lon: 125.75, lat: 39.02 },
  { name: 'islamabad', country: 'pakistan', continent: 'asie', lon: 73.06, lat: 33.68 },
  { name: 'malé', country: 'maldives', continent: 'asie', lon: 73.51, lat: 4.18 },
  { name: 'jakarta', country: 'indonésie', continent: 'asie', lon: 106.85, lat: -6.21 },
  { name: 'kuala lumpur', country: 'malaisie', continent: 'asie', lon: 101.69, lat: 3.14 },
  { name: 'dacca', country: 'bangladesh', continent: 'asie', lon: 90.41, lat: 23.81 },
  { name: 'douchanbé', country: 'tadjikistan', continent: 'asie', lon: 68.78, lat: 38.54 },
  { name: 'bakou', country: 'azerbaïdjan', continent: 'asie', lon: 49.87, lat: 40.41 },
  { name: 'beyrouth', country: 'liban', continent: 'asie', lon: 35.5, lat: 33.89 },
  { name: 'tbilissi', country: 'géorgie', continent: 'asie', lon: 44.79, lat: 41.72 },
  { name: 'copenhague', country: 'danemark', continent: 'europe', lon: 12.57, lat: 55.68 },
  { name: 'apia', country: 'samoa', continent: 'océanie', lon: -171.75, lat: -13.85 },
  { name: 'rome', country: 'italie', continent: 'europe', lon: 12.5, lat: 41.9 },
  { name: 'windhoek', country: 'namibie', continent: 'afrique', lon: 17.08, lat: -22.57 },
  { name: 'zagreb', country: 'croatie', continent: 'europe', lon: 15.98, lat: 45.81 },
  { name: 'ljubljana', country: 'slovénie', continent: 'europe', lon: 14.51, lat: 46.06 },
  { name: 'banjul', country: 'gambie', continent: 'afrique', lon: -16.58, lat: 13.45 },
  { name: 'le caire', country: 'égypte', continent: 'afrique', lon: 31.24, lat: 30.04 },
  { name: 'damas', country: 'syrie', continent: 'asie', lon: 36.28, lat: 33.51 },
  { name: 'bissau', country: 'guinée-bissau', continent: 'afrique', lon: -15.6, lat: 11.86 },
  { name: 'caracas', country: 'venezuela', continent: 'amérique du sud', lon: -66.9, lat: 10.48 },
  { name: 'harare', country: 'zimbabwe', continent: 'afrique', lon: 31.05, lat: -17.83 },
  { name: 'lomé', country: 'togo', continent: 'afrique', lon: 1.22, lat: 6.13 },
  { name: 'brazzaville', country: 'congo', continent: 'afrique', lon: 15.24, lat: -4.26 },
  { name: 'mbabane', country: 'eswatini', continent: 'afrique', lon: 31.14, lat: -26.32 },
  { name: 'panama', country: 'panama', continent: 'amérique du nord', lon: -79.52, lat: 8.98 },
  { name: 'tirana', country: 'albanie', continent: 'europe', lon: 19.82, lat: 41.33 },
  { name: 'managua', country: 'nicaragua', continent: 'amérique du nord', lon: -86.25, lat: 12.11 },
  { name: 'san josé', country: 'costa rica', continent: 'amérique du nord', lon: -84.08, lat: 9.93 },
  { name: 'las vegas', country: 'états-unis', continent: 'amérique du nord', lon: -115.14, lat: 36.17 },
  { name: 'vancouver', country: 'canada', continent: 'amérique du nord', lon: -123.12, lat: 49.28 },
  { name: 'new york', country: 'états-unis', continent: 'amérique du nord', lon: -74.01, lat: 40.71 },
  { name: 'georgetown', country: 'guyana', continent: 'amérique du sud', lon: -58.16, lat: 6.8 },
  { name: 'asuncion', country: 'paraguay', continent: 'amérique du sud', lon: -57.58, lat: -25.3 },
  { name: 'mexico', country: 'mexique', continent: 'amérique du nord', lon: -99.13, lat: 19.43 },
  { name: 'berne', country: 'suisse', continent: 'europe', lon: 7.45, lat: 46.95 },
  { name: 'vilnius', country: 'lituanie', continent: 'europe', lon: 25.28, lat: 54.69 },
  { name: 'riga', country: 'lettonie', continent: 'europe', lon: 24.11, lat: 56.95 },
  { name: 'djibouti', country: 'djibouti', continent: 'afrique', lon: 43.15, lat: 11.59 },
  { name: 'buenos aires', country: 'argentine', continent: 'amérique du sud', lon: -58.38, lat: -34.61 },
  { name: 'amsterdam', country: 'pays-bas', continent: 'europe', lon: 4.9, lat: 52.37 },
  { name: 'reykjavik', country: 'islande', continent: 'europe', lon: -21.94, lat: 64.15 },
  { name: 'montevideo', country: 'uruguay', continent: 'amérique du sud', lon: -56.16, lat: -34.9 },
  { name: 'sarajevo', country: 'bosnie-herzégovine', continent: 'europe', lon: 18.41, lat: 43.86 },
  { name: 'dodoma', country: 'tanzanie', continent: 'afrique', lon: 35.74, lat: -6.16 },
  { name: 'yaoundé', country: 'cameroun', continent: 'afrique', lon: 11.5, lat: 3.87 },
  { name: 'washington', country: 'états-unis', continent: 'amérique du nord', lon: -77.04, lat: 38.91 },
  { name: 'lilongwe', country: 'malawi', continent: 'afrique', lon: 33.78, lat: -13.96 },
  { name: 'nouakchott', country: 'mauritanie', continent: 'afrique', lon: -15.98, lat: 18.09 },
  { name: 'kampala', country: 'ouganda', continent: 'afrique', lon: 32.58, lat: 0.35 },
  { name: 'abuja', country: 'nigeria', continent: 'afrique', lon: 7.49, lat: 9.08 },
  { name: 'kaboul', country: 'afghanistan', continent: 'asie', lon: 69.21, lat: 34.56 },
  { name: 'maputo', country: 'mozambique', continent: 'afrique', lon: 32.58, lat: -25.97 },
  { name: 'berlin', country: 'allemagne', continent: 'europe', lon: 13.4, lat: 52.52 },
  { name: 'asmara', country: 'érythrée', continent: 'afrique', lon: 38.93, lat: 15.32 },
  { name: 'luxembourg', country: 'luxembourg', continent: 'europe', lon: 6.13, lat: 49.61 },
  { name: 'téhéran', country: 'iran', continent: 'asie', lon: 51.42, lat: 35.69 },
  { name: 'bichkek', country: 'kirghizistan', continent: 'asie', lon: 74.6, lat: 42.87 },
  { name: 'são paulo', country: 'brésil', continent: 'amérique du sud', lon: -46.63, lat: -23.55 },
  { name: 'bangkok', country: 'thaïlande', continent: 'asie', lon: 100.5, lat: 13.75 },
  { name: 'libreville', country: 'gabon', continent: 'afrique', lon: 9.45, lat: 0.39 },
  { name: 'moscou', country: 'russie', continent: 'europe', lon: 37.62, lat: 55.75 },
  { name: 'tunis', country: 'tunisie', continent: 'afrique', lon: 10.18, lat: 36.81 },
  { name: 'accra', country: 'ghana', continent: 'afrique', lon: -0.19, lat: 5.6 },
  { name: 'prague', country: 'république tchèque', continent: 'europe', lon: 14.42, lat: 50.09 },
  { name: 'port-louis', country: 'maurice', continent: 'afrique', lon: 57.5, lat: -20.16 },
  { name: 'achgabat', country: 'turkménistan', continent: 'asie', lon: 58.38, lat: 37.95 },
  { name: 'santiago', country: 'chili', continent: 'amérique du sud', lon: -70.65, lat: -33.45 },
  { name: 'n\'djamena', country: 'tchad', continent: 'afrique', lon: 15.06, lat: 12.13 },
  { name: 'riyad', country: 'arabie saoudite', continent: 'asie', lon: 46.72, lat: 24.71 },
  { name: 'madrid', country: 'espagne', continent: 'europe', lon: -3.7, lat: 40.42 },
  { name: 'thimphou', country: 'bhoutan', continent: 'asie', lon: 89.64, lat: 27.47 },
  { name: 'katmandou', country: 'népal', continent: 'asie', lon: 85.19, lat: 27.42 },
  { name: 'bratislava', country: 'slovaquie', continent: 'europe', lon: 17.06, lat: 48.08 },
  { name: 'shanghai', country: 'chine', continent: 'asie', lon: 121.28, lat: 31.13 },
  { name: 'amman', country: 'jordanie', continent: 'asie', lon: 35.56, lat: 31.57 },
  { name: 'bucarest', country: 'roumanie', continent: 'europe', lon: 26.06, lat: 44.25 },
  { name: 'bujumbura', country: 'burundi', continent: 'afrique', lon: 29.21, lat: -3.22 },
  { name: 'doha', country: 'qatar', continent: 'asie', lon: 51.31, lat: 25.16 },
  { name: 'yamoussoukro', country: 'côte d\'ivoire', continent: 'afrique', lon: -5.16, lat: 6.49 },
  { name: 'helsinki', country: 'finlande', continent: 'europe', lon: 24.56, lat: 60.1 },
  { name: 'tallinn', country: 'estonie', continent: 'europe', lon: 24.45, lat: 59.26 },
  { name: 'belgrade', country: 'serbie', continent: 'europe', lon: 20.27, lat: 44.48 },
  { name: 'abou dabi', country: 'émirats arabes unis', continent: 'asie', lon: 54.22, lat: 24.28 },
  { name: 'conakry', country: 'guinée', continent: 'afrique', lon: -13.4, lat: 9.32 },
  { name: 'antananarivo', country: 'madagascar', continent: 'afrique', lon: 47.31, lat: -18.54 },
  { name: 'melbourne', country: 'australie', continent: 'océanie', lon: 144.57, lat: -37.48 },
  { name: 'podgorica', country: 'monténégro', continent: 'europe', lon: 19.16, lat: 42.26 },
  { name: 'bagdad', country: 'irak', continent: 'asie', lon: 44.23, lat: 33.18 },
  { name: 'honolulu', country: 'états-unis', continent: 'océanie', lon: -157.51, lat: 21.18 },
  { name: 'dakar', country: 'sénégal', continent: 'afrique', lon: -17.2, lat: 14.45 },
  { name: 'oslo', country: 'norvège', continent: 'europe', lon: 10.44, lat: 59.54 },
  { name: 'brasilia', country: 'brésil', continent: 'amérique du sud', lon: -47.55, lat: -15.46 },
  { name: 'athènes', country: 'grèce', continent: 'europe', lon: 23.42, lat: 37.58 },
  { name: 'astana', country: 'kazakhstan', continent: 'asie', lon: 71.26, lat: 51.1 },
  { name: 'malabo', country: 'guinée équatoriale', continent: 'afrique', lon: 8.47, lat: 3.45 },
  { name: 'suva', country: 'fidji', continent: 'océanie', lon: 178.26, lat: -18.08 },
  { name: 'pékin', country: 'chine', continent: 'asie', lon: 116.24, lat: 39.54 },
  { name: 'bandar seri begawan', country: 'brunei', continent: 'asie', lon: 114.56, lat: 4.56 },
  { name: 'mogadiscio', country: 'somalie', continent: 'afrique', lon: 45.21, lat: 2.02 },
  { name: 'tokyo', country: 'japon', continent: 'asie', lon: 139.42, lat: 35.41 },
  { name: 'séoul', country: 'corée du sud', continent: 'asie', lon: 126.58, lat: 37.33 },
  { name: 'alger', country: 'algérie', continent: 'afrique', lon: 3.02, lat: 36.45 },
  { name: 'tegucigalpa', country: 'honduras', continent: 'amérique du nord', lon: -87.12, lat: 14.04 },
  { name: 'nairobi', country: 'kenya', continent: 'afrique', lon: 36.49, lat: -1.17 },
  { name: 'la valette', country: 'malte', continent: 'europe', lon: 14.3, lat: 35.53 },
  { name: 'kinshasa', country: 'république démocratique du congo', continent: 'afrique', lon: 15.19, lat: -4.19 },
  { name: 'port-au-prince', country: 'haïti', continent: 'amérique du nord', lon: -72.2, lat: 18.32 },
  { name: 'sucre', country: 'bolivie', continent: 'amérique du sud', lon: -65.15, lat: -19.02 },
  { name: 'minsk', country: 'biélorussie', continent: 'europe', lon: 27.34, lat: 53.54 },
  { name: 'maseru', country: 'lesotho', continent: 'afrique', lon: 27.28, lat: -29.18 },
  { name: 'honiara', country: 'îles salomon', continent: 'océanie', lon: 159.57, lat: -9.26 },
  { name: 'quito', country: 'équateur', continent: 'amérique du sud', lon: -78.31, lat: -0.13 },
  { name: 'rio de janeiro', country: 'brésil', continent: 'amérique du sud', lon: -43.12, lat: -22.54 },
  { name: 'hanoi', country: 'vietnam', continent: 'asie', lon: 105.57, lat: 21.01 },
  { name: 'chisinau', country: 'moldavie', continent: 'europe', lon: 28.5, lat: 47.01 },
  { name: 'praia', country: 'cap-vert', continent: 'afrique', lon: -23.3, lat: 14.55 },
  { name: 'addis abbeba', country: 'éthiopie', continent: 'afrique', lon: 38.44, lat: 9.01 },
];
